export type codeType =
  | 'BAD_REQUEST'
  | 'UNAUTHORIZED'
  | 'FORBIDDEN'
  | 'NOT_FOUND'
  | 'TOO_MANY_REQUESTS'
  | 'INTERNAL_SERVER_ERROR'
  | 'USER_ALREADY_EXISTS'
  | 'USER_NOT_FOUND'
  | 'NOT_ACCESSED'
  | 'NOT_FOUND_EMAIL'
  | 'DIFFERENT_PASSWORD'
  | 'NOT_FOUND'
  | 'BLOCK_USER'
  | 'ACCOUNT_NOT_FOUND'
  | 'REGISTER_INCLUDE';

const code = {
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER_ERROR: 500,
  USER_ALREADY_EXISTS: 1001,
  USER_NOT_FOUND: 1000,
  NOT_ACCESSED: 1002,
  NOT_FOUND_EMAIL: 1005,
  DIFFERENT_PASSWORD: 1006,
  BLOCK_USER: 1008,
  ACCOUNT_NOT_FOUND: 1009,
  REGISTER_INCLUDE: 1010,
};

export default code;
